### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by ccliuyang** [ccsdu2004/snailstock#1]
缺少
```
per/StockPerData.h、finance\StockFinance.cpp、per\StockPerData.cpp、qrc目录下的两个脚本文件
```

**Comment by ccsdu2004** [comment]
晚上饿改下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月2日(周三) 上午6:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ccsdu2004/snailstock] 编译不通过 (#1)




 
缺少
 per/StockPerData.h、finance\StockFinance.cpp、per\StockPerData.cpp、qrc目录下的两个脚本文件

**Comment by ccsdu2004** [comment]
已处理
